# Generated by Django 4.1.1 on 2022-10-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImRecetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='recetas')),
                ('nombre', models.CharField(max_length=30)),
                ('ingredientes', models.CharField(max_length=240)),
                ('tiempo', models.IntegerField()),
                ('preparacion', models.TextField(max_length=720)),
            ],
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Musica',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
