# Generated by Django 4.1.1 on 2022-10-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGl', '0002_imrecetas_receta_delete_libro_delete_musica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(max_length=1200),
        ),
    ]
